development:
  cloud_name: <your_cloud_name>
  api_key: <your_api_key>
  api_secret: <your_api_secret>
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: <your_cloud_name>
  api_key: <your_api_key>
  api_secret: <your_api_secret>
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: <your_cloud_name>
  api_key: <your_api_key>
  api_secret: <your_api_secret>
  enhance_image_tag: true
  static_file_support: false
